### ISSUE TITLE
already Rust pyd build, but can't running.

### ISSUE THREAD

**Issue by startmuscle0731** [Waelwindows/blender_mot_plugin#1]
I thought I probably needed to build the rust project contained in your repository to run this blender add-on. 

I tried diva_db and mot_new. The build succeeds, but I get a "dynamic module does not define module export function" error. 
The following message is PyInit__diva_db or mot). I thought maybe my build settings were wrong in this regard. 
Modules usually seem to be declared in lib.rs.

I wondered if it would work if I added the module definition that exists in py_ffi to lib.rs, but I didn't. Looking at other tutorials etc., I added a function and succeeded in calling Hello, world !, etc., but still did not succeed in calling mot and diva_db. Can you give me some hints?

**Comment by startmuscle0731** [comment]
I have already used the minmode script and applied IK in blender to get some good motion. 
I'm not sure because I still can't build the required modules properly, can this plugin handle Inverse Kinematics properly?

Looking at the file exported by the minmode script, the DIVA skeleton does not have a "pole" used by IK. This was mentioned in the past by minmode itself. I can't get 100% accurate foot movements.

**Comment by ArcadeGamer1929** [comment]
Did you ever manage to fix this? I'm getting the same error with PyInit_mot
